#!/bin/bash
p_name=lampi
p_author='Md Jahidul Hamid'
p_source='https://github.com/neurobin/lampi'
p_bugt="$p_source/issues"
p_version=0.0.1
ver_info="
Name        : $p_name
Version     : $p_version
Author      : $p_author
Source      : $p_source
Bug tracker : $p_bugt
"
help="
######################### lampi #############################
# Lamp stack installer for Ubuntu (14.04/16.04)
#############################################################
# Usage:
#   lampi [-v, -h, -dr, -s]
# Run simply lampi to install the lamp stack
# with default configs
#
# Options:
#   [ -v, --version ]       : show version info
#   [ -h, --help ]          : show help
#   [ -i, --install ]       : install lamp
#   [ -dr, --doc-root ]     : arbitrary document root
#   [ -s, --ssl ]           : enable SSL       
#   [ -nu, --no-update ]    : do not run apt-get update
#   [ -ni, --no-install ]   : skip install process
#   [ -n, --name ]          : server name (default localhost)
##############################################################
"
dr=''
ssl=false
no_update=false
install=false
localhost=localhost
for op in "$@";do
    case "$op" in
        -v|--version)
            echo "$ver_info"
            shift
            exit 0
            ;;
        -h|--help)
            echo "$help"
            shift
            exit 0
            ;;
        -dr|--doc-root)
            shift
            dr="${1/%\//}"
            shift
            ;;
        -s|--ssl)
            ssl=true
            shift
            ;;
        -nu|--no-update)
            no_update=true
            shift
            ;;
        -i|--install)
            install=true
            shift
            ;;
        -n|--name)
            shift
            if [[ "$1" != "" ]]; then
                localhost="$1"
                shift
            else
                echo "E: Arg missing for -n option"
                exit 1
            fi
            ;;
        "")
        ## dummy, empty arg is swallowed
        ;;
        -*)
            echo "E: Invalid option: $1"
            shift
            exit 1
            ;;
    esac
done

[ "$dr" = "" ] && dr='/var/www/html'

mkdir -p "$dr"

#check for root
if [ $EUID -ne 0 ]; then
    printf "\n\tRoot privilege required\n"
    printf "\tSorry! Exiting\n\n"
    exit 1
fi

#extract dist version
rel=(`lsb_release -r | grep -o '[0-9]\+'`)
rv=${rel[0]}

tphp='
<?php
phpinfo();
?>
'

if $install; then

    #update
    if ! $no_update;then apt-get update;fi

    #apache2 and mysql
    list=(
    'apache2'
    'mysql-server'
    'mysql-client'
    )

    #mysql
    if [ "$rv" = '14' ];then
        mysql="php5-mysql"
    elif [ "$rv" = '16' ];then
        mysql="php-mysql"
    fi
    for i in $mysql;do
        list+=("$i")
    done

    #php
    if [ "$rv" = '14' ];then
        php='php5 libapache2-mod-php5 php5-mcrypt php5-cgi php5-cli php5-common php5-curl php5-gd'
    elif [ "$rv" = '16' ];then
        php='php libapache2-mod-php php-mcrypt php-cgi php-cli php-common php-curl php-gd'
    fi
    for i in $php;do
        list+=("$i")
    done

    #phpmyadmin
    phpmd='phpmyadmin apache2-utils'
    for i in $phpmd;do
        list+=("$i")
    done

    for app in ${list[@]};do
        echo "Installing: $app"
        apt-get -y install $app || 
        apt-get -y install --reinstall $app || {
        echo "W: Failed to install: $app"
        [ "$app" = apache2 ] && exit 1
        [ "$app" = php ] && exit 1
        [ "$app" = php5 ] && exit 1
        }
    done
fi
#create info.php
echo "$tphp" > "$dr"/info.php

aconf=/etc/apache2/apache2.conf
pdconf=/etc/phpmyadmin/apache.conf
pdincl="Include $pdconf"
if ! grep -s -e "$pdincl" "$aconf" >/dev/null 2>&1; then
    sed -i.bak "$ a $pdincl" "$aconf"
fi

dire="\t<Directory $dr>\n\t\tAllowOverride All\n\t\tOptions Indexes FollowSymLinks MultiViews\n\t\tOrder allow,deny\n\t\tRequire all granted\n\t\tAllow from all\n\t\t\n\t</Directory>\n"

#custom sites
ds='/etc/apache2/sites-available/000-default.conf'
ds_ssl='/etc/apache2/sites-available/default-ssl.conf'
dsn="$(dirname "$ds")/$localhost.conf"
ds_ssln="$(dirname "$ds_ssl")/$localhost-ssl.conf"

export localhost
export dr
export dire
copy_default_config(){
    sed  -e "s=^\([[:blank:]]*DocumentRoot\).*$=\1 $dr="\
               -e "s=^\([[:blank:]]*ServerName\).*$=\1 $localhost="\
               -e "s=^\([[:blank:]]*<[[:blank:]]*Directory[[:blank:]]*\)[^[:blank:]]\+\([[:blank:]]*>[[:blank:]]*\)$=\1$dr\2="\
               -e "s=^\([[:blank:]]*<[[:blank:]]*VirtualHost[[:blank:]]*\)[^:]*\(:[^>]*>[[:blank:]]*\)$=\1 127.0.0.1\2="\
               "$1" > "$2"
}

copy_default_config "$ds" "$dsn"
copy_default_config "$ds_ssl" "$ds_ssln"

insert_server_property(){
    if ! grep -s -e "^\([[:blank:]]*$1\).*$" "$2" >/dev/null 2>&1; then
        sed -i.bak -e "s=^[[:blank:]]*<[[:blank:]]*VirtualHost[[:blank:]]*.*>[[:blank:]]*$=&\n\tServerName $localhost=" "$2"
    fi
}
insert_server_property ServerName "$dsn"
insert_server_property ServerName "$ds_ssln"

insert_docroot_property(){
    if ! grep -s -e "^[[:blank:]]*<[[:blank:]]*Directory[[:blank:]]*[^[:blank:]]\+[[:blank:]]*>[[:blank:]]*$" "$1" >/dev/null 2>&1; then
        sed -i.bak -e "s=^\([[:blank:]]*\)DocumentRoot.*$=&\n$dire=" "$1"
    fi
}

insert_docroot_property "$dsn"
insert_docroot_property "$ds_ssln"



if ! grep -s -e "^127.0.0.1[[:blank:]]*$localhost[[:blank:]]*$" /etc/hosts >/dev/null 2>&1; then
    sed -i.bak -e "1 a 127.0.0.1\t$localhost" /etc/hosts
fi

#enable mods
a2enmod rewrite
if $ssl; then a2enmod ssl;fi

#enable sites
a2ensite "$localhost"
if $ssl; then a2ensite "$localhost"-ssl;fi
#restart the apache2 service
service apache2 restart

echo "
*****
Visit $localhost/info.php
"
